### ISSUE TITLE
The Terminal Icon is not visible

### ISSUE THREAD

**Issue by OSINTAI** [deepklarity/jupyter-text2code#19]
The installation worked correctly.  The Terminal Icon is not visible a shown in the demo. Is there a way to activate it?
Thanks

**Comment by dk-crazydiv** [comment]
Maybe it's the same issue as #17 . When `jupyter notebook` is run, print statements on the console will show if the backend extension loaded correctly and the model is downloaded from tensorflow_hub. nbextension configuration could be a reason terminal icon is not visible. The extension named `jupyter_text2code` should be enabled.

**Comment by OSINTAI** [comment]
Thanks. It worked. :)

This extension in Jupyter helps activating the invisible extensions:
`https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator `

**Comment by lilanqing-kk** [comment]
My installation seems not successful, could you please help diagnose the reason? 
------
loading_jupyter_server_extension: jupyter-text2code. First install will download universal-sentence-encoder, please wait...
********************
********************
[W 18:33:06.958 NotebookApp] Error loading server extension jupyter_text2code.jupyter_text2code_serverextension
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
        self.send(msg)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
        self.connect()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
        server_hostname=server_hostname)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
        _context=self, _session=session)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
        self.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
        self._sslobj.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

**Comment by dk-dsr** [comment]
We have updated the installation instructions and also published docker images. Please reopen if issue not resolved.

**Comment by dk-dsr** [comment]
We have updated the installation instructions and also published docker images. Please reopen if issue not resolved.
